# Generated by Django 6.0.4 on 2026-05-05 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('specialty', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artisans/')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('wool', 'Laine'), ('cotton', 'Coton'), ('silk', 'Soie'), ('thread', 'Fil')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('m', 'Mètre'), ('piece', 'Pièce')], default='kg', max_length=20)),
                ('purchase_date', models.DateField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='artisans.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='artisans.artisan')),
            ],
        ),
    ]
