# Generated by Django 6.0.4 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('wool', 'Laine'), ('cotton', 'Coton'), ('silk', 'Soie'), ('thread', 'Fil'), ('Argile', 'Argile'), ('Silver', 'Argent')], max_length=50),
        ),
    ]
